version: '3.8'

services:
  vue-local-dev:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: [ "npm", "run", "dev" ]
